# Generated by Django 2.2 on 2023-04-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm',
            name='Mission',
            field=models.TextField(blank=True, help_text='max of 400 words', max_length=400),
        ),
    ]
