# Generated by Django 2.2 on 2023-06-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arms', '0002_auto_20230412_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm',
            name='Arm_image',
            field=models.ImageField(upload_to='assets/Arms'),
        ),
        migrations.AlterField(
            model_name='arm_detail',
            name='image_beside',
            field=models.ImageField(upload_to='assets/Arms image beside'),
        ),
    ]
