# Generated by Django 2.2 on 2023-04-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations_and_Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Payment_description', models.CharField(max_length=300)),
                ('ref', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
                ('verified', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-Date_Created',),
            },
        ),
    ]
