# Generated by Django 2.2 on 2023-06-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_auto_20230601_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations_and_support',
            name='Partnership_type',
            field=models.CharField(choices=[('One Time', 'One Time'), ('Monthly Recurrent', 'Monthly Recurrent')], default='None', max_length=300),
        ),
    ]
