# Generated by Django 2.2 on 2023-04-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Other_Venue',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
