# Generated by Django 2.2 on 2023-06-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20230613_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='S_N',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='photo',
            name='S_N',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='S_N',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='staff',
            name='S_N',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='value',
            name='S_N',
            field=models.IntegerField(default=1),
        ),
    ]
