# Generated by Django 2.2 on 2023-07-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20230629_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='GEM_Arm',
            field=models.CharField(choices=[('Bible Studies', 'Bible Studies'), ('Revival Prayer', 'Revival Prayer'), ('Foundation', 'Foundation'), ('Women’s Hub', 'Women’s Hub'), ('Partners', 'Partners')], default='None', max_length=300),
        ),
    ]
